-- AlterTable
ALTER TABLE `Game` ADD COLUMN `places` INTEGER NOT NULL DEFAULT 100;

-- AlterTable
ALTER TABLE `Reservation` ADD COLUMN `place` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `uniqueCode` INTEGER NOT NULL DEFAULT 0;
